"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

APP = ['run.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
